---
name: Continous Integration - Main

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '32 6 * * *' # set random cron

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: irishlab-io/admin/.github/workflows/reusable-ggshield.yml@main
    secrets: inherit

  hello-world:
    needs: secret
    name: Call Hello World
    uses: irishlab-io/pipelines/.github/workflows/reusable-hello-world.yml@main
    with:
      comments: "4321tset"
      enable: false
