---
name: Reusable - GH Labeler

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      configuration_file:
        description: GH Labeler configuration
        required: false
        default: ".github/labeler.yml"
        type: string
  workflow_dispatch:

jobs:
  labeler:
    name: Run GH labler
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          configuration-path: ${{ inputs.configuration_file }}

      - name: Sync Labels
        uses: EndBug/label-sync@v2.3.3
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
